### ISSUE TITLE
How to run migration manager on install version?

### ISSUE THREAD

**Issue by MaxHasADHD** [fortinmike/MFMigrationManager#3]
I'm currently writing 1.2 version of my app, how would I run this to migrate from the previous version of the app without the migration manager?

**Comment by matt-curtis** [comment]
Was just thinking about this. There's no way to know what version of the app your user is coming from, if you only start tracking versions in a later release. Here's the solution I came up with:
1. On app start, you check for the presence of key, say in `NSUserDefaults` (or somewhere), like `LastRunVersion`, or `IsUsingMigrationManager`. If this key exists, you know that whatever version the user is upgrading from was tracking the last run version, and you do migration business as usual.
2. If this key _doesn't_ exist, then you know whatever version they're upgrading from _was not_ tracking the running app version. You know the last release that didn't set this key was, maybe `1.0`, etc. So now you know that they're upgrading from `1.0` or less. For typical intents and purposes, you can say 'for sure' that they're upgrading from `1.0`. So now you can tell your migration logic the user is upgrading from <= `1.0` ;)

Now, we just need `MFMigrationManager` to implement some logic like this, and give us more details on how it's storing versions/migrations... :)

EDIT: You can just set `MFMigrationManagerLastVersionKey` in `NSUserDefaults` (see source) but a nicer way would be great

**Comment by fortinmike** [comment]
Sorry for the delay answering to this.

Yes, what was suggested by @matt-curtis in his edit would be the way to go (using `MFMigrationManagerLastVersionKey`). To me it seems like a pretty straightforward way to add `MFMigrationManager` to an existing app. I'm not sure additional API surface would be justified in this case. Maybe this just needs to be documented?

In any case, if you think an API would be substantially better let me know what you have in mind and I'll consider. I don't have much time to work on this ATM but I'd gladly accept a quality pull request (with tests if appropriate) :)
